### ISSUE TITLE
Windows Analytics Database Connect

### ISSUE THREAD

**Issue by kevinmainairungu** [ekitabu-LLC/ekitabu-readium-desktop-working#51] opened 2020-12-01 20:17 UTC
Hi @mocyeg We are epxerience an issue in trying to access the analtycs database. See screenshot attached below. We also can't access the same instance on Azure. 
<img width="1440" alt="Screen Shot 2020-12-01 at 11 15 14 PM" src="https://user-images.githubusercontent.com/23236275/100792072-27bf0400-342b-11eb-974f-22f5414f0802.png">

**Comment by mocyeg** [comment] 2020-12-03 04:11
Duplicate of https://github.com/ekitabu-LLC/home/issues/9

**Closed by mocyeg** 2020-12-03 04:11 UTC
Labels: bug
